'use strict';

// Event Outcome Indicator
exports.OUTCOME_SUCCESS = 0;
exports.OUTCOME_MINOR_FAILURE = 4;
exports.OUTCOME_SERIOUS_FAILURE = 8;
exports.OUTCOME_MAJOR_FAILURE = 12;

// Network Access Point Type Code
exports.EVENT_ACTION_CREATE = 'C';
exports.EVENT_ACTION_READ = 'R';
exports.EVENT_ACTION_UPDATE = 'U';
exports.EVENT_ACTION_DELETE = 'D';
exports.EVENT_ACTION_EXECUTE = 'E';

// Network Access Point Type Code
exports.NET_AP_TYPE_DNS = 1;
exports.NET_AP_TYPE_IP = 2;
exports.NET_AP_TYPE_TEL = 3;

// Audit Source Type Code
exports.AUDIT_SRC_TYPE_UI = 1;
exports.AUDIT_SRC_TYPE_DATA_AQUISITION = 2;
exports.AUDIT_SRC_TYPE_WEB_SERVER = 3;
exports.AUDIT_SRC_TYPE_APP_SERVER = 4;
exports.AUDIT_SRC_TYPE_DB_SERVER = 5;
exports.AUDIT_SRC_TYPE_SECURITY_SERVER = 6;
exports.AUDIT_SRC_TYPE_NET_COMP = 7;
exports.AUDIT_SRC_TYPE_OS = 8;
exports.AUDIT_SRC_TYPE_EXTERN = 9;

// Participant Object Type Code
exports.OBJ_TYPE_PERSON = 1;
exports.OBJ_TYPE_SYS_OBJ = 2;
exports.OBJ_TYPE_ORG = 3;
exports.OBJ_TYPE_OTHER = 4;

// Participant Object Type Code Role
exports.OBJ_TYPE_CODE_ROLE_PATIENT = 1;
exports.OBJ_TYPE_CODE_ROLE_LOCATION = 2;
exports.OBJ_TYPE_CODE_ROLE_REPORT = 3;
exports.OBJ_TYPE_CODE_ROLE_RESOURCE = 4;
exports.OBJ_TYPE_CODE_ROLE_MASTER_FILE = 5;
exports.OBJ_TYPE_CODE_ROLE_USER = 6;
exports.OBJ_TYPE_CODE_ROLE_LIST = 7;
exports.OBJ_TYPE_CODE_ROLE_DOCTOR = 8;
exports.OBJ_TYPE_CODE_ROLE_SUBSCRIBER = 9;
exports.OBJ_TYPE_CODE_ROLE_GUARANTOR = 10;
exports.OBJ_TYPE_CODE_ROLE_SECURITY_USER_ENTITY = 11;
exports.OBJ_TYPE_CODE_ROLE_SECURITY_USER_GROUP = 12;
exports.OBJ_TYPE_CODE_ROLE_SECURITY_RESOURCE = 13;
exports.OBJ_TYPE_CODE_ROLE_SECURITY_GRANULARITY = 14;
exports.OBJ_TYPE_CODE_ROLE_PROVIDER = 15;
exports.OBJ_TYPE_CODE_ROLE_DATA_DESTINATION = 16;
exports.OBJ_TYPE_CODE_ROLE_DATA_REPOSITORY = 17;
exports.OBJ_TYPE_CODE_ROLE_SCHEDULE = 18;
exports.OBJ_TYPE_CODE_ROLE_CUSTOMER = 19;
exports.OBJ_TYPE_CODE_ROLE_JOB = 20;
exports.OBJ_TYPE_CODE_ROLE_JOB_STREAM = 21;
exports.OBJ_TYPE_CODE_ROLE_QUERY = 24;

// Participant Object ID Type Code
exports.OBJ_ID_TYPE_MRN = 1;
exports.OBJ_ID_TYPE_PAT_NUM = 2;
exports.OBJ_ID_TYPE_ENCOUNTER_NUM = 3;
exports.OBJ_ID_TYPE_ENROLLEE_NUM = 4;
exports.OBJ_ID_TYPE_SSN = 5;
exports.OBJ_ID_TYPE_ACC_NUM = 6;
exports.OBJ_ID_TYPE_GUARANTOR_NUM = 7;
exports.OBJ_ID_TYPE_REPORT_NAME = 8;
exports.OBJ_ID_TYPE_REPORT_NUM = 9;
exports.OBJ_ID_TYPE_SEARCH_CRIT = 10;
exports.OBJ_ID_TYPE_USER_ID = 11;
exports.OBJ_ID_TYPE_URI = 12;
